apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-setup
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: setup
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-kibana-secrets
                key: ELASTIC_PASSWORD
          - name: KIBANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-kibana-secrets
                key: KIBANA_PASSWORD
        command: [ "bash", "-c" ]
        args:
          - >
            echo "Waiting for Elasticsearch to be available...";
            until curl -s -u elastic:${ELASTIC_PASSWORD} http://elasticsearch:9200/_cluster/health | grep -q '"status":"'; do
              echo "Elasticsearch not yet available, sleeping 10s...";
              sleep 10;
            done;

            echo "Setting kibana_system password...";
            until curl -s -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" \
              -X POST http://elasticsearch:9200/_security/user/kibana_system/_password \
              -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do
              echo "Retrying set kibana_system password...";
              sleep 10;
            done;

            echo "Creating index template for logstash-*...";
            curl -s -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" \
              -X PUT http://elasticsearch:9200/_template/logstash_template \
              -d '{
                "index_patterns": ["logstash-*"],
                "mappings": {
                  "properties": {
                    "message": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword",
                          "ignore_above": 256
                        }
                      }
                    },
                    "commUpd.id": {
                      "type": "integer"
                    },
                    "commUpd.articol": {
                      "type": "text"
                    },
                    "commUpd.id_furniz": {
                      "type": "integer"
                    },
                    "commUpd.furnizor": {
                      "type": "text"
                    },
                    "commUpd.nr_zile": {
                      "type": "integer"
                    }
                  }
                }
              }';

            echo "All done!";