apiVersion: batch/v1
kind: Job
metadata:
  name: init-elasticsearch
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init-es
          image: curlimages/curl:7.88.1
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo "Elasticsearch is up! Creating test-index..."
              curl -X PUT http://elasticsearch:9200/test-index \
                   -H 'Content-Type: application/json' \
                   -d '{"settings":{"number_of_shards":1,"number_of_replicas":0}}'

              echo "Done!"

              echo "All done!";             
  backoffLimit: 4